# Generated by Django 5.1.3 on 2024-11-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_bedrooms', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Brian',
        ),
    ]
