# Generated by Django 5.1.3 on 2024-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_house_delete_brian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emmanuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='num_bedrooms',
        ),
    ]
