# Generated by Django 5.1.3 on 2024-12-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_emmanuel_remove_house_num_bedrooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emmanuel',
            new_name='Brian',
        ),
    ]
