# Generated by Django 5.1.3 on 2024-12-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_emmanuel_brian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brian',
            new_name='Chair',
        ),
    ]
