# Generated by Django 5.1.3 on 2024-12-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_brian_chair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chair',
            new_name='Cars',
        ),
    ]
